Configuration:
  status: "warn"
  properties:
    property:
      -
        name: app-name
        value: config
      -
        name: log-path
        value: C:/tmp/logs
      -
        name: log-file
        value: ${app-name}.log
      -
        name: archive
        value: ${app-name}.log.gz

  Appenders:
    Console:
      name: "console"
      PatternLayout:
        pattern: "%d{yyyy/MM/dd HH:mm:ss.SSS} %-5level - %m%n"
    RollingFile:
      name: "file"
      fileName: ${log-path}/${log-file}
      filePattern: ${log-path}/%d{yyyy-MM-dd}_${archive}
      PatternLayout:
        pattern: "%d{yyyy/MM/dd HH:mm:ss.SSS} %-5level - %m%n"
      Policies:
        TimeBasedTriggeringPolicy: {}
  Loggers:
    Logger:
    - name: "trylog4j2yaml"
      level: "debug"
      additivity: "false"
      AppenderRef:
      - ref: "console"
      - ref: "file"
    - name: "org.hibernate.type.descriptor.sql"
      level: "trace"
      additivity: "false"
      AppenderRef:
      - ref: "console"
      - ref: "file"
    Root:
      level: "info"
      AppenderRef:
      - ref: "console"
      - ref: "file"